# Generated by Django 6.0.3 on 2026-03-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventcategory_event_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
