# Generated by Django 6.0.3 on 2026-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
