# Generated by Django 6.0.3 on 2026-03-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_venue_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='image_url',
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
