# Generated by Django 6.0.4 on 2026-04-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_venue_image_url_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
