# Generated by Django 6.0.4 on 2026-04-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_payment_stripe_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='exist',
            new_name='if_exist',
        ),
    ]
